---
# tasks file for mytom7DeployOnRedHat



- name: Download the war file and keep in webapps folder
  get_url:
    url: https://s3-ap-southeast-1.amazonaws.com/maha4iac/SKRlogin.war
    dest:  /usr/share/tomcat/webapps/
    force_basic_auth: yes
  notify: restarttom7
  when: ansible_os_family =="RedHat"
